import {
  DESIGN_SYSTEM_META,
  type DesignSystem,
  type DesignSystemMeta,
  type DesignType,
} from './types.js';

/**
 * Deterministic artifact renderer — branded self-contained HTML from a
 * brief (no LLM, no CDN, no image model). The agent loop (Docs/34 §9)
 * replaces this starter with real `write_file` output later; the pane's
 * Code tab edits the same `artifact.html` either way.
 */

/** HTML-escape user text before it touches the artifact. */
export function escHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Split a brief into 1-4 short display sentences. */
export function briefSentences(brief: string): string[] {
  const parts = brief
    .split(/[\n;]+|\.\s+/)
    .map((s) => s.replace(/^[-*> ]+/, '').trim().replace(/\s+/g, ' '))
    .filter((s) => s.length > 0)
    .slice(0, 4);
  return parts.length > 0 ? parts : ['Untitled artifact'];
}

/** Short words (>=4 chars) become card labels — deterministic, no NLP. */
export function briefKeywords(brief: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const word of brief.split(/[^a-zA-Z0-9#+]+/)) {
    const w = word.trim();
    if (w.length >= 4 && !seen.has(w.toLowerCase())) {
      seen.add(w.toLowerCase());
      out.push(w.slice(0, 18));
    }
    if (out.length >= 6) break;
  }
  return out.length > 0 ? out : ['Lokma', 'Design', 'Studio'];
}

function cssBase(meta: DesignSystemMeta): string {
  return `body{font-family:${meta.font};padding:28px;background:${meta.bg};color:${meta.ink};margin:0}h1{font-size:22px;margin:0 0 6px}h2{font-size:15px;margin:0 0 8px;color:${meta.accent}}.sub{color:${meta.muted};font-size:12px;line-height:1.6;margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.card{padding:16px;border:1px solid ${meta.line};border-radius:12px;background:${meta.surface}}.card strong{font-size:13px}.card p{font-size:11px;color:${meta.muted};line-height:1.5;margin:6px 0 0}.pill{display:inline-block;padding:2px 10px;border-radius:999px;background:${meta.accentSoft};border:1px solid ${meta.line};color:${meta.accent};font-size:11px;margin-bottom:12px}.cta{display:inline-block;margin-top:14px;padding:8px 18px;border-radius:8px;background:${meta.accent};color:#fff;font-size:12px}footer{margin-top:22px;font-size:10px;color:${meta.muted}}`;
}

function docShell(meta: DesignSystemMeta, title: string, body: string): string {
  return `<html><head><meta charset="utf-8"><style>${cssBase(meta)}</style></head><body><span class="pill">${escHtml(title)}</span><h1>${escHtml(title)}</h1><p class="sub">Generated by Lokma Design Studio · ${escHtml(meta.name)} tokens · edit in the Code tab</p>${body}<footer>DESIGN.md brand contract · ${escHtml(meta.tokens)}</footer></body></html>`;
}

/** Hue from a string hash — the `image` scaffold art is deterministic. */
export function hueFor(text: string): number {
  let h = 0;
  for (let i = 0; i < text.length; i += 1) h = (h * 31 + text.charCodeAt(i)) % 360;
  return h;
}

function buildPrototype(brief: string, meta: DesignSystemMeta): string {
  const sentences = briefSentences(brief);
  const keywords = briefKeywords(brief);
  const tiers = [sentences[0] ?? brief, sentences[1] ?? keywords[0] ?? 'Pro', sentences[2] ?? keywords[1] ?? 'Scale'];
  const cards = tiers
    .map(
      (t, i) =>
        `<div class="card"><strong>Tier ${i + 1} · ${escHtml(t.slice(0, 42))}</strong><p>${escHtml(sentences[i % sentences.length] as string)}</p><span class="cta">Choose</span></div>`,
    )
    .join('');
  return docShell(meta, sentences[0]?.slice(0, 60) ?? 'Prototype', `<div class="grid">${cards}</div>`);
}

function buildDeck(brief: string, meta: DesignSystemMeta): string {
  const sentences = briefSentences(brief);
  const slides = sentences
    .map(
      (s, i) =>
        `<div class="card" style="margin-bottom:12px"><h2>Slide ${i + 1}</h2><strong>${escHtml(s.slice(0, 60))}</strong><p>${escHtml(s)}</p></div>`,
    )
    .join('');
  return docShell(meta, `Deck · ${(sentences[0] ?? 'Pitch').slice(0, 48)}`, slides);
}

function buildMobile(brief: string, meta: DesignSystemMeta): string {
  const sentences = briefSentences(brief);
  const rows = briefKeywords(brief)
    .slice(0, 4)
    .map((k) => `<div class="card" style="margin-bottom:10px"><strong>${escHtml(k)}</strong><p>${escHtml(sentences[0] ?? '')}</p></div>`)
    .join('');
  return docShell(
    meta,
    `Mobile · ${(sentences[0] ?? 'App').slice(0, 48)}`,
    `<div style="max-width:340px;margin:0 auto;border:2px solid ${meta.line};border-radius:24px;padding:14px;background:${meta.surface}">${rows}</div>`,
  );
}

function buildImage(brief: string, meta: DesignSystemMeta): string {
  // No image model in the harness — a deterministic SVG composition holds
  // the slot until a provider-backed generator lands (honest scope note).
  const hue = hueFor(brief);
  const keywords = briefKeywords(brief).slice(0, 3);
  const circles = keywords
    .map(
      (k, i) =>
        `<circle cx="${90 + i * 110}" cy="${100 + (i % 2) * 40}" r="${44 - i * 8}" fill="hsl(${(hue + i * 40) % 360} 60% 55% / 0.75)"/><text x="${90 + i * 110}" y="${104 + (i % 2) * 40}" text-anchor="middle" font-size="11" fill="#fff">${escHtml(k)}</text>`,
    )
    .join('');
  return docShell(
    meta,
    `Image · ${keywords[0] ?? 'Art'}`,
    `<div class="card"><svg viewBox="0 0 400 220" style="width:100%;border-radius:8px;background:${meta.accentSoft}"><rect width="400" height="220" fill="hsl(${hue} 45% 92%)"/>${circles}</svg><p>SVG placeholder composition — a provider image model (GPT Image / Seedream / FAL) renders the final here.</p></div>`,
  );
}

function buildDocument(brief: string, meta: DesignSystemMeta): string {
  const sentences = briefSentences(brief);
  const sections = sentences
    .map((s) => `<h2>${escHtml(s.slice(0, 48))}</h2><p class="sub">${escHtml(s)}</p>`)
    .join('');
  return docShell(meta, `Document · ${(sentences[0] ?? 'Notes').slice(0, 48)}`, `<div class="card">${sections}</div>`);
}

function buildHyperframe(brief: string, meta: DesignSystemMeta): string {
  const sentences = briefSentences(brief);
  const steps = sentences
    .map((s, i) => `<div class="frame f${i}"><strong>${i + 1} · ${escHtml(s.slice(0, 44))}</strong><p>${escHtml(s)}</p></div>`)
    .join('');
  const frames = sentences.map((_, i) => `.f${i}{animation:rise 6s infinite;animation-delay:${i * 1.5}s;opacity:0}`).join('');
  return `<html><head><meta charset="utf-8"><style>${cssBase(meta)}.stage{position:relative;min-height:220px}.frame{position:absolute;inset:0;padding:18px;border:1px solid ${meta.line};border-radius:12px;background:${meta.surface}}${frames}@keyframes rise{0%{opacity:0;transform:translateY(14px)}8%,28%{opacity:1;transform:none}36%,100%{opacity:0}}.timeline{margin-top:12px;font-size:10px;color:${meta.muted};font-family:monospace}</style></head><body><span class="pill">hyperframe · timeline</span><h1>${escHtml((sentences[0] ?? 'Motion').slice(0, 60))}</h1><p class="sub">CSS keyframe storyboard — MP4 render (HyperFrames / ffmpeg) is a follow-up</p><div class="stage">${steps}</div><div class="timeline">t+0.0s → t+${(sentences.length * 1.5).toFixed(1)}s · ${sentences.length} frames · finite trace</div></body></html>`;
}

/**
 * Build the starter artifact HTML for a type+brief+system triple.
 * Always returns a complete self-contained document (fails closed —
 * unknown types never reach here, `store.ts` validates first).
 */
export function buildArtifactHtml(type: DesignType, brief: string, system: DesignSystem): string {
  const meta = DESIGN_SYSTEM_META[system];
  switch (type) {
    case 'prototype':
      return buildPrototype(brief, meta);
    case 'deck':
      return buildDeck(brief, meta);
    case 'mobile':
      return buildMobile(brief, meta);
    case 'image':
      return buildImage(brief, meta);
    case 'document':
      return buildDocument(brief, meta);
    case 'hyperframe':
      return buildHyperframe(brief, meta);
  }
}
